version: "3.8"
services:
  courtyard:
    build: './courtyard'
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  stable:
    build: ./stable
    ports:
      - "5000:5000"
  barn:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'Users'
      MYSQL_USER: 'outsideaccess'
      MYSQL_PASSWORD: 'db_pw_123'
      MYSQL_ROOT_PASSWORD: 'db_pw_123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
  guard-dog:
    image: "redis:alpine"
    command: redis-server --requirepass account_access_123
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
  myadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: barn
      PMA_USER: root
      PMA_PASSWORD: db_pw_123
    ports:
      - "8080:80"
    depends_on:
      - barn
volumes:
  mysql: